### ISSUE TITLE
Predicted results in the model

### ISSUE THREAD

**Issue by debmalya97** [cerlymarco/MEDIUM_NoteBook#11]
Hi

I was confused on how to get the predicted average price which the model has learnt after this code-

```
### DEFINE LSTM FORECASTER ###
inputs2 = Input(shape=(X_train2.shape[1], X_train2.shape[2]))
lstm2 = LSTM(128, return_sequences=True, dropout=0.3)(inputs2, training=True)
lstm2 = LSTM(32, return_sequences=False, dropout=0.3)(lstm2, training=True)
dense2 = Dense(50)(lstm2)
out2 = Dense(1)(dense2)

model2 = Model(inputs2, out2)
model2.compile(loss='mse', optimizer='adam', metrics=['mse'])

### FIT FORECASTER ###
history = model2.fit(X_train2, y_train2, epochs=30, batch_size=128, verbose=2, shuffle=True)
```

**Comment by cerlymarco** [comment]
Hi, welcome back

I don't understand your doubt, could you please be more specific?

**Comment by debmalya97** [comment]
I wanted the results from the LSTM model to compare with the actual data. What code is doing that?

**Comment by cerlymarco** [comment]
In my code, the function stoc_drop1 and stoc_drop2 make exactly this. I wrote this function because they are useful to me to adopt STOCHASTIC DROPOUT (which is one of the core ideas). If you are looking for some simpler, MAE(y_test2, model.predict(X_test2)) it's ok
Bye
