### ISSUE TITLE
Some questions about the "Graph_TimeSeries_Forecasting" code.

### ISSUE THREAD

**Issue by momochendyy** [cerlymarco/MEDIUM_NoteBook#13]
Hi, I am very interested in the part of "Graph_TimeSeries_Forecasting", but I cannot download the full article in "README.md". Is it an academic paper? Can you tell me the name of this article or the website of the article? Thank you very much!

**Comment by cerlymarco** [comment]
Hi, it's a link to a blog published to Toward Data Science: https://towardsdatascience.com/time-series-forecasting-with-graph-convolutional-neural-network-7ffb3b70afcf
