### ISSUE TITLE
time in Extreme_Event_Forecasting

### ISSUE THREAD

**Issue by tankwin08** [cerlymarco/MEDIUM_NoteBook#14]
Hi Marco,
Thanks very much for the good work.
I have one question on time in avocado.csv. The date column is not really from the earliest to the latest. The year followed the right order, but the date starts from Dec to Jan for each year.
But we used LSTM, do you think this will affect your final results? Or this format is for another purpose.

Many thanks.

Best
Tan

**Comment by cerlymarco** [comment]
Hi, I've uploaded the correct notebook... don't forget to stay connected on medium or to leave a star

thank you
all the best
