### ISSUE TITLE
Extreme_Event_Forecasting.ipynb

### ISSUE THREAD

**Issue by alessandroibrahim99** [cerlymarco/MEDIUM_NoteBook#2]
Hello Marco,

Amazing code ! I have just a small problem when I run it. I have the error "ValueError: Found input variables with inconsistent numbers of samples: [848, 16]" 

When I run below : 

### COMPUTE STOCHASTIC DROPOUT FOR SINGLE COUNTY ###
mae2_test = []
for i in tqdm.tqdm(range(0,100)):
    mae2_test.append(mean_absolute_error(test_stoc_drop2('TotalUS', 0.5)[0], y2_test))
print(np.mean(mae2_test), np.std(mae2_test))

ValueError                                Traceback (most recent call last)
<ipython-input-32-a055995a9637> in <module>
      2 mae2_test = []
      3 for i in tqdm.tqdm(range(0,100)):
----> 4     mae2_test.append(mean_absolute_error(test_stoc_drop2('TotalUS', 0.5)[0], y2_test))
      5 
      6 print(np.mean(mae2_test), np.std(mae2_test))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\regression.py in mean_absolute_error(y_true, y_pred, sample_weight, multioutput)
    170     """
    171     y_type, y_true, y_pred, multioutput = _check_reg_targets(
--> 172         y_true, y_pred, multioutput)
    173     check_consistent_length(y_true, y_pred, sample_weight)
    174     output_errors = np.average(np.abs(y_pred - y_true),

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\regression.py in _check_reg_targets(y_true, y_pred, multioutput)
     75 
     76     """
---> 77     check_consistent_length(y_true, y_pred)
     78     y_true = check_array(y_true, ensure_2d=False)
     79     y_pred = check_array(y_pred, ensure_2d=False)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py in check_consistent_length(*arrays)
    203     if len(uniques) > 1:
    204         raise ValueError("Found input variables with inconsistent numbers of"
--> 205                          " samples: %r" % [int(l) for l in lengths])
    206 
    207 

ValueError: Found input variables with inconsistent numbers of samples: [848, 16]

---------------------------------------------

Could you help me please ?
thanks

**Comment by cerlymarco** [comment]
Hi, thanks for this useful feedback!

I check and correct the error... I simple remake the function 'test_stoc_drop2', this will solve the problem

Thanks a lot... all the best!
Ciao

**Comment by siinem** [comment]
Dear Marco,
I am not able to access the article on this issue on Medium. Could you please share with me at siinem@gmail.com?
I would be appreciated,

Best
Sinem

**Comment by cerlymarco** [comment]
Hi @siinem, I'm sorry but can't do anything about this

https://github.com/cerlymarco/MEDIUM_NoteBook/issues/5
