### ISSUE TITLE
ValueError: Dimensions must be equal, but are 2 and 1 for

### ISSUE THREAD

**Issue by 1rashiid** [cerlymarco/MEDIUM_NoteBook#22]
Could you please tell the dimension for the case where the input_dim=4, and the output_dim=3. During my implementation, I have some problem with this part of the code:
class T2V(Layer):
    def __init__(self, output_dim = None, **kwargs):
        self.output_dim = output_dim
        super(T2V, self).__init__(**kwargs)        
    def build(self, input_shape):
        self.W = self.add_weight(name='W', shape=(1, self.output_dim), initializer='uniform', trainable=True)
        self.P = self.add_weight(name='P',shape=(1, self.output_dim),initializer='uniform',trainable=True)
        self.w = self.add_weight(name='w',shape=(1,1),initializer='uniform', trainable=True)
        self.p = self.add_weight(name='p',shape=(1,1),initializer='uniform',trainable=True)
        super(T2V, self).build(input_shape)
  for one input and one output it works well. But I don't know how to set the dimension for the other cases. Thanks

**Comment by cerlymarco** [comment]
Hi, 

T2V is implemented to deal with time sequences in 3D format. Think also about LSTM/GRU, you can't use it with 4D data

Thanks
