### ISSUE TITLE
ONE-class neural network

### ISSUE THREAD

**Issue by hasamkhalid** [cerlymarco/MEDIUM_NoteBook#24]
When i run the code block :

tf.random.set_random_seed(33)
os.environ['PYTHONHASHSEED'] = str(33)
np.random.seed(33)
random.seed(33)

session_conf = tf.compat.v1.ConfigProto(
    intra_op_parallelism_threads=1, 
    inter_op_parallelism_threads=1
)
sess = tf.Session()
    graph=tf.compat.v1.get_default_graph(), 
    config=session_conf
)
tf.compat.v1.keras.backend.set_session(sess)
es = EarlyStopping(monitor='val_loss', mode='auto', restore_best_weights=True, verbose=1, patience=5)
model = get_model()
model.fit(wrap_generator(train_generator), steps_per_epoch=train_generator.samples/train_generator.batch_size, epochs=20)

I Get this Error!

InvalidArgumentError: Requested tensor connection from unknown node: "dense_2_target:0".

**Comment by cerlymarco** [comment]
just tested the same code on a simply dummy dataset...

This error doesn't appear: https://colab.research.google.com/drive/1FcuJTFC9m8A2JJj7Ge3kiJVpbhFpa8f5?usp=sharing

Maybe u made some wrong manipulation to the network or u use an old tf/keras version

it's difficult to say more

**Comment by hasamkhalid** [comment]
> just tested the same code on a simply dummy dataset...
> 
> This error doesn't appear: https://colab.research.google.com/drive/1dLzsXNTKVHdavI-CfV3lezJgojjK3iEx?usp=sharing
> 
> Maybe u made some wrong manipulation to the network or u use an old tf/keras version
> 
> it's difficult to say more

I didn't do anything to the model. just running the same code on my local machine. Tried keras version 2.0.0, 2.4.0 as well but same error. The complete log is as below:


Epoch 1/20
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\api\_v1\keras\optimizers\__init__.py in <module>
     20 
     21 model = get_model()
---> 22 model.fit(wrap_generator(train_generator), steps_per_epoch=train_generator.samples/train_generator.batch_size, epochs=20)

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    671           use_multiprocessing=use_multiprocessing,
    672           shuffle=shuffle,
--> 673           initial_epoch=initial_epoch)
    674     if training_utils.is_eager_dataset_or_iterator(x):
    675       # Make sure that y, sample_weights, validation_split are not passed.

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1431         shuffle=shuffle,
   1432         initial_epoch=initial_epoch,
-> 1433         steps_name='steps_per_epoch')
   1434 
   1435   def evaluate_generator(self,

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\engine\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    262 
    263       is_deferred = not model._is_compiled
--> 264       batch_outs = batch_function(*batch_data)
    265       if not isinstance(batch_outs, list):
    266         batch_outs = [batch_outs]

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\engine\training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1173       self._update_sample_weight_modes(sample_weights=sample_weights)
   1174       self._make_train_function()
-> 1175       outputs = self.train_function(ins)  # pylint: disable=not-callable
   1176 
   1177     if reset_metrics:

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\backend.py in __call__(self, inputs)
   3287         feed_symbols != self._feed_symbols or self.fetches != self._fetches or
   3288         session != self._session):
-> 3289       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   3290 
   3291     fetched = self._callable_fn(*array_vals,

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\keras\backend.py in _make_callable(self, feed_arrays, feed_symbols, symbol_vals, session)
   3220       callable_opts.run_options.CopyFrom(self.run_options)
   3221     # Create callable.
-> 3222     callable_fn = session._make_callable_from_options(callable_opts)
   3223     # Cache parameters corresponding to the generated callable, so that
   3224     # we can detect future mismatches and refresh the callable.

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\client\session.py in _make_callable_from_options(self, callable_options)
   1487     """
   1488     self._extend_graph()
-> 1489     return BaseSession._Callable(self, callable_options)
   1490 
   1491 

~\anaconda3\envs\keras-env\lib\site-packages\tensorflow\python\client\session.py in __init__(self, session, callable_options)
   1444       try:
   1445         self._handle = tf_session.TF_SessionMakeCallable(
-> 1446             session._session, options_ptr)
   1447       finally:
   1448         tf_session.TF_DeleteBuffer(options_ptr)

InvalidArgumentError: Requested tensor connection from unknown node: "dense_5_target:0".

**Comment by paulaceccon** [comment]
Same here.
