### ISSUE TITLE
TimeSeries_Smoothing_Clustering.ipynb

### ISSUE THREAD

**Issue by waudinio27** [cerlymarco/MEDIUM_NoteBook#26]
I wanted to ask if it is possible to use this notebook for forecasting as well with the predict function from tslearn as well together with tsmoothie ....
And if so - could you be so kind and show how to predict 1 or 2 time steps ahead with the according python code to try it out?

One more additional question I have - would you recommend the TimeSeries_Smoothing_Forecasting notebook for financial data as well? I am quite curious. 

Thanks a lot for your effort and answer

Matthias

**Comment by cerlymarco** [comment]
Hi, thanks for your support

You can use time series smoothing as preprocessing of your prediction task and use it with sklearn, tslearn, sktime, tensorflow or whatever u want. You simply have to reproduce the smoothing every time you make a prediction. So we are at time T... if u want to predict T+1, u simply have to smooth [T:T-n] and feed the smoothed series in your pipeline.

I never recommend to predict financial data.

All the best
