### ISSUE TITLE
Accuracy always 0.0 

### ISSUE THREAD

**Issue by snairgopika** [cerlymarco/MEDIUM_NoteBook#29]
I used the program as such on cat dog dataset..even after training for reasonable epochs "print(accuracy)" shows 0.0 . Is it just my problem or dataset problem or anything else . Pls reply and thank you for your hard work shared.

**Comment by cerlymarco** [comment]
This is normal... We can't expect to replicate the same procedures and methods on any task and expect the same results. The oneclass NN applied on the dog-cat dataset is only an example of how to use a oneclass approach with NN (as described in the paper). It's our duty to analyze the data at our disposal and, according to this, develop the best ML pipeline.

"All models are wrong, but some are useful".
