### ISSUE TITLE
NeuralNet_ensemble

### ISSUE THREAD

**Issue by kavi0786** [cerlymarco/MEDIUM_NoteBook#32]
Sir, 
         I executed the neural network ensemble model successfully. Finally, how we can test the unseen image to get the model predictions. Thanks in advance . I am waiting for your reply.

Kavitha

**Comment by cerlymarco** [comment]
Hi, this is shown in the notebook...

`np.argmax(model.predict(test_generator), axis=1)` for generators

`np.argmax(model.predict(img), axis=1)` for single image in array format

**Comment by kavi0786** [comment]
Sir,  
    I executed the line "np.argmax(model.predict(test_generator), axis=1)" . It is showing the following...
(https://user-images.githubusercontent.com/41922876/127433186-98399511-e50b-427a-85e4-33a04aeced54.png).

I executed the line "np.argmax(model.predict(img), axis=1)" it is showing the following...
(https://user-images.githubusercontent.com/41922876/127433463-e49d3d02-fc74-4b62-8fb4-07e188935fc5.png).

sir, i need the output like below.
1. first it will accept one image from test data
2. After it will show the image with predicted and original label name...

please do the needful.

Thanks in advance...

Kavitha

**Comment by cerlymarco** [comment]
In your example img is a simple string... you have to call model.predict(img) with img as an **array** of shape (1, width, height, n_channel)

**Comment by ApicaSharma15** [comment]
Sir, if we have a FAVAR model . what changes do u recommend in the codes?
