### ISSUE TITLE
FAVAR with LSTM

### ISSUE THREAD

**Issue by ApicaSharma15** [cerlymarco/MEDIUM_NoteBook#33]
Sir, for a FAVAR model what changes do you recommend in the codes?

**Comment by cerlymarco** [comment]
Hi, which notebook of mine this question is related to?

Could you be more precise. Thanks

**Comment by ApicaSharma15** [comment]
Sir, this is regarding combining LSTM and VAR. 
Similar context if we combine LSTM and FAVAR what changes do you recommend.
Awaiting your response.

**Comment by cerlymarco** [comment]
The method presented in the notebook is independent from the algorithms used. This means you can change it according to your needs
