### ISSUE TITLE
VAE _timeseries or Multivariate timeseries input

### ISSUE THREAD

**Issue by hojatb** [cerlymarco/MEDIUM_NoteBook#34]
Dear Marco
Thank you for sharing the VAE_timeseries codes. 
1. I want to use that for Multivariate time series reconstruction. but it gives me error in modeling in several parts. do you have sample code for multivariate ones as well?
2. Is that possible to modify the model to predict by itself the categories of reconstructed dataset as well? I mean  that the decoder part only gets the Z latent vector and produces the reconstruction dataset together with the categorical attributes?
I tried for both cases unsuccessful!
thanks
hojat

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback

I appreciate your interest and I imagine you made some effort in reproducing the analysis, however, I think I can not answer these questions...

First of all, I don't know the errors you get. Secondly, you are correctly adapting the code to your case but this forces me to debug your code and this is out of the scope of this repository. This would be great but I have no time to take care of everyone's problems.

So if you have problems reproducing exactly the same analysis of my notebook, this is the right place. If you are looking for someone who adapts the code to your needs, I'm sorry but I can't do it.

All the best
