### ISSUE TITLE
One class Neural network issue

### ISSUE THREAD

**Issue by RichardChangCA** [cerlymarco/MEDIUM_NoteBook#35]
Hello,

I used the one class CNN codes for cat/dog classification, but when I only use cat images as training and test on cat/dog data, my trained model predict all test samples as cat, which means it cannot detect the anomalies. Since there is a bug in my tensorflow 2.1 version, I only changed the code from " pre_process = Lambda(preprocess_input)" to "pre_process = preprocess_input". The rest are same. I do not know why, could you also provide the dataset, please?

**Comment by cerlymarco** [comment]
Hi, what I suggest u is to follow the blog [here ](https://towardsdatascience.com/one-class-neural-network-in-keras-249ff56201c0). The dataset is linked there.

You already have the access to the code and [here](https://colab.research.google.com/drive/1FcuJTFC9m8A2JJj7Ge3kiJVpbhFpa8f5?usp=sharing) I provide a dummy example to debug the code if you are interested.

All the best
