### ISSUE TITLE
Request for translation and reprinting to Chinese community

### ISSUE THREAD

**Issue by AlvinIsonomia** [cerlymarco/MEDIUM_NoteBook#36]
Thank you for your great articles and notebooks! They inspired me a lot when I was struggling to get started with anomaly detection tasks ：） 

May I translate your articles into Chinese and repost it to the Chinese Community (namely ZHIHU)?  If approval I will point out their original source. In addition, I am more accustomed to using Pytorch, so I hope to add the modified code when reprinting. Similarly, I will declare its original developer and reposity.

**Comment by cerlymarco** [comment]
Hi, you are welcome! This would be super useful!

Feel free to translate, copy/change/improve code. Citing the original sources (my blog post on Medium or my github repos) it's enough.

Thanks again for your effort!
