### ISSUE TITLE
I couldn't install the Shaphypetune package through PIP or Conda 

### ISSUE THREAD

**Issue by bigdaronlee163** [cerlymarco/MEDIUM_NoteBook#37]
https://github.com/cerlymarco/MEDIUM_NoteBook/tree/master/ShapBoruta_FeatureSelection

**Comment by cerlymarco** [comment]
simply running `pip install --upgrade shap-hypetune` works!

https://colab.research.google.com/drive/1_KHWlH6sLEyPtbZ-9W7Vlg7931YHTPbC?usp=sharing
