### ISSUE TITLE
Different predictions for the same dataset

### ISSUE THREAD

**Issue by luisgustavob78** [cerlymarco/MEDIUM_NoteBook#40]
Hi Marco, how are you?

I am using your code for extreme event forecasting  and I have a problem when predicting the new features: after the training process in a first notebook, I saved the architecture and the weights from the encoder model (encoder=Model(inputs_ae, encoded_ae)). When I load the layers and the weights in a second notebook, each time I run this second notebook, using the same dataset, I get different results generated by the "encoder.predict(X_train)". Do you have any suspects why it is happening?

Thanks a lot for this material mate, great stuff.

**Comment by cerlymarco** [comment]
Hi, it's difficult for me to say anything about that problem with the information u provided... This is a known issue that I hope u can solve by looking [around](https://stackoverflow.com/questions/54744552/different-prediction-after-load-a-model-in-keras).
If u support the project don't forget to leave a star ;-)
