### ISSUE TITLE
VAE+LSTM for missing value imputation with a univariate time series

### ISSUE THREAD

**Issue by Aminsn** [cerlymarco/MEDIUM_NoteBook#41]
Hello Marco, I was wondering if you can replicate your post: https://towardsdatascience.com/time-series-generation-with-vae-lstm-5a6426365a1c but without the categorical variables? I tried to do it but the model performed really bad.

**Comment by cerlymarco** [comment]
Hi, thanks for your feedback

Generally speaking, we can't expect to replicate the same procedures and methods on any task and expect great results. In this repo are shown examples of how to apply some techniques. It's our duty to analyze the data at our disposal and, according to this, develop the best ML pipeline.

I appreciate your interest and I imagine you made some effort in reproducing the analysis, however, I think I can not answer this question. If you have problems reproducing exactly the same analysis of my notebook, this is the right place. If you are looking for someone who adapts the code to your needs, I'm sorry but I've no time to do it.

All the best
