### ISSUE TITLE
Hello, I want to contact you plz

### ISSUE THREAD

**Issue by anizima** [cerlymarco/MEDIUM_NoteBook#42]

**Comment by cerlymarco** [comment]
Hi, thanks for your interest but you should elaborate...

You can ask whatever you want, however, **take care of these points**:
- If you have problems reproducing exactly the same analysis in my notebook, this is the right place to ask. 
- If you are looking for someone who adapts the code to your needs, I'm sorry but I can't do it.

All the best

**Comment by anizima** [comment]
Thank you for your response.
Acutly I had the code and report for my research, but I need your experience and support to enhance my work based on your knowledge. I was searching for your freelancer account and not find.

Please your support.

On 26 Nov 2022, at 3:08 PM, Marco Cerliani ***@***.***> wrote:

﻿

Hi, thanks for your interest but you should elaborate...

You can ask whatever you want, however, take care of these points:

  *   If you have problems reproducing exactly the same analysis in my notebook, this is the right place to ask.
  *   If you are looking for someone who adapts the code to your needs, I'm sorry but I can't do it.

All the best
