### ISSUE TITLE
DFM and tspiral

### ISSUE THREAD

**Issue by waudinio27** [cerlymarco/MEDIUM_NoteBook#44]
Your models are great. Can you also show an example with strong trend?

**Comment by cerlymarco** [comment]
Hi, thanks for your interest! 
you can easily integrate this behavior in the notebook! The data are simulated so you can modify them according to your needs. Adding a trend is straightforward in that case.

As a last point...

_the perfect forecasting technique that suits all situations doesn’t exist. As data scientists, we are responsible to experiment with techniques we don’t know before_

All the best
