### ISSUE TITLE
ValueError: cannot reshape array of size 25690112 into shape (50625,512)

### ISSUE THREAD

**Issue by vaibhav030798** [cerlymarco/MEDIUM_NoteBook#45]
my image size = 225 
and ERROR is -

---> 23     out = np.dot(activation_maps.reshape((img.shape[0]*img.shape[1], 512)), class_weights).reshape(img.shape[0],img.shape[1])
     24 
     25 

ValueError: cannot reshape array of size 25690112 into shape (50625,512)

**Comment by cerlymarco** [comment]
Hi, 

- It's difficult to understand an error without context.
- If you have problems reproducing exactly the same analysis in my notebooks, this is the right place to ask.
- If you are looking for someone who adapts the code to your needs, I'm sorry but I can't do it.

All the best
