### ISSUE TITLE
TimeSeries_Cluster : standardized data values clipped to nearest integer

### ISSUE THREAD

**Issue by bazzaar** [cerlymarco/MEDIUM_NoteBook#47]
@cerlymarco, Hi and many thanks for making your work available in this repo, it's an invaluable resource for a ML newbie like me.

Recently I've been thinking about clustering time series to ensure that the input dataset is focussed for the ML modelling phase.

Therefore, the TimeSeries_Cluster article (and code) is of particular interest to me.

In trying to understand the various steps in the code presented, it seems that the standardized data values are all clipped to the nearest integer. I think this is due to employing the ```pd.df.values``` method, and the dtype of the individual ndarrays is automatically selected as integer (as all the initial data values are integers).

If, instead of using ```.values``` to build the initial list of np.ndarrays, we use ```.to_numpy(dtype=np.float32)``` then the standardized data are no longer clipped. 

This makes a significant difference to the dendrograms.

Perhaps, I'm not understanding the data preparation process correctly, anyway I hope the above observation is of use.

**Comment by cerlymarco** [comment]
Hi, thanks for your interest!

In the code, there isn't any clipping/rounding behavior defined. It's simply used the default configurations of pandas.

 If u support the project, don't forget to leave a star.
All the best

**Comment by bazzaar** [comment]
I've left a star, as I do value the project very much :+1: 

And I do understand that rounding of values was maybe not specifically intended in the code, however it still does seem to be happening.

I added only the print statement (to show the 1st row of **standardized** values from each time series)
```
### STANDARDIZE DATA ###
for i,s in enumerate(data):
    data[i] = (data[i] - s.mean(axis=0)) / s.std(axis=0)
    print(data[i][:1,:])
```
This outputs:

```
[[0 0 1]]
[[ 0  0 -1]]
[[-1  0  0]]
[[-1  0  0]]
[[0 0 0]]
[[0 2 1]]
[[-2  1  0]]
[[-2  0  0]]
[[0 0 0]]
[[0 0 0]]
[[ 0 -1  0]]
[[0 0 0]]
[[ 0 -1  0]]
[[0 0 1]]
[[-1  1  1]]
[[-1  0 -3]]
[[-2  2  0]]
[[-2  0  0]]
[[0 0 1]]
[[0 0 2]]
```

If I additionally modify the READ (**raw**) DATA step like so:
```
    measure = pd.read_csv('Walk_MODEL/'+txt, sep=' ', header=None).to_numpy(dtype=np.float32)
    # measure = pd.read_csv('Walk_MODEL/'+txt, sep=' ', header=None).values
```
, the **standardized** data  prints like so:

```
[[-0.24377148  0.8999427   1.2165844 ]]
[[-0.0864997 -0.3183289 -1.8747538]]
[[-1.034917   -0.20026775 -0.6284234 ]]
[[-1.2767165  0.3949876  0.0617862]]
[[-0.94585687 -0.6917572   0.22346972]]
[[0.3477024 2.4035242 1.1265535]]
[[-2.7368045  1.7351995 -0.7061621]]
[[-2.0357776   0.8325706   0.42645484]]
[[-0.00147682 -0.16817702 -0.05114021]]
[[0.19428909 0.97471255 0.30308715]]
[[ 0.91625327 -1.2403107   0.12919234]]
[[0.78307015 0.20589393 0.5234043 ]]
[[-0.12794082 -1.0869471   0.51053464]]
[[0.7802715 0.6026999 1.5734447]]
[[-1.9107251  1.5160508  1.0231315]]
[[-1.6241772 -0.9992452 -3.0500765]]
[[-2.9596987   2.5448432   0.54526025]]
[[-2.1728208   0.837506    0.30342144]]
[[ 0.04737149 -0.29277578  1.5044067 ]]
[[0.32223907 0.49042943 2.8768256 ]]
```

These real numbers are what would be expected after subtracting the mean, and then dividing by the stdev.

As stated in my initial comment, the impact of the rounding in the **standardized** data makes a difference in the final dendograms.
