### ISSUE TITLE
Time series bootstrapping bug 

### ISSUE THREAD

**Issue by msh855** [cerlymarco/MEDIUM_NoteBook#53]
Hi, 
Thank you for tsmoothie. It is a nice library that I often use. 

I am trying to bootstrap time series data using the `'nbb'  as a bootstrapping method. I am always getting this error: 

```
bootstrap_res = residuals[[0], bootstrap_id]
IndexError: index 18590 is out of bounds for axis 1 with size 18590
```

Here a MWE that you can reproduce the error
```

import yfinance
data = yfinance.download('^GSPC')
ret = data['Adj Close'].pct_change()
btype = ['nbb', 'mbb', 'cbb', 'sb'][0]
spc = SpectralSmoother(smooth_fraction=0.18, pad_len=12)
bts = BootstrappingWrapper(spc, bootstrap_type=btype, block_length=24)
bts_samples = bts.sample(data=ret.dropna(), n_samples=10)
```

It looks like the `nbb ' does not take into account the sample size of the original data.

**Comment by cerlymarco** [comment]
Thanks for reporting this!
It's fixed in the new tsmoothie version (1.0.5)

`pip install --upgrade tsmoothie`

If u support the projects, don't forget to leave a star ;-)
